source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'YLBProUI_Example' do
  # 基础库
  pod 'YLBCommon', :git =>'https://github.com/ProBobo/YLBCommon.git'
  # UI库
  pod 'YLBProUI', :path => '../'

  target 'YLBProUI_Tests' do
    inherit! :search_paths

    
  end
end
